### ISSUE TITLE
CLI tool for setting up remote jobs (especially batch)

### ISSUE THREAD

**Issue by jonnor** [imgflo/imgflo-server#26]
Usecases:
- color-grading frames for a movie
- cropping/resizing from shots of same scene

Begs the question whether the server itself should have some batch supporting APIs, see #25

**Comment by bergie** [comment]
I've been using [ImageMagick](http://www.imagemagick.org/) a lot for that kind of jobs. ImgFlo would be a lot more powerful, and allow offloading the heavy lifting to some cheap cloud workers.

**Comment by jonnor** [comment]
No batch API support, but `imgflo-url` NPM package now has a CLI tool with same name that can be convenient to produce request URLs at least. https://www.npmjs.com/package/imgflo-url#create-an-imgflo-url-using-commandline

**Comment by jonnor** [comment]
Out of scope
