### ISSUE TITLE
Switch NoFlo runner to noflo-nodejs

### ISSUE THREAD

**Issue by bergie** [imgflo/imgflo-server#56]
Currently imgflo-server is executing NoFlo graphs via the `noflo` command, which will be removed in 0.6: noflo/noflo#297

https://github.com/jonnor/imgflo-server/blob/970f519a19c6f5fded08154045a9a0cd4d8c197b/src/noflo.coffee#L39

Should use noflo-nodejs instead. This also has the additional benefit of adding component loader cache support needed for #55

**Comment by jonnor** [comment]
Branch `noflo-cache`.
Fixed some things in noflo-nodejs, but it needs some `--port=auto` feature also for concurrency to work.

But even with a single request, the network never stops. Tested with `TESTS=1977 make check`.

By my reckoning these component all have broken behavior. But I don't know right fixes, either network ended prematurely or never stopped. CC/ @bergie

* `canvas/CreateCanvas` and `canvas/CreateCanvas-node` - missing disconnect() ?
* `canvas/Draw`- missing connect handling/forwarding?
* `noflo-helper-arrayable` (basecomponent for bunch of canvas components) - missing disconnect() ?
* *  `image/CreateImage` and  `image/CreateImage-node` - possibly missing connect/disconnect unless AsyncComponent takes care of it

**Comment by jonnor** [comment]
Probably best way forward is to make some tests in noflo-image, with simple graphs ran with noflo-nodejs. For instance one which just loads file and saves it again, then one that does some simple processing. And just verify that the process exits as expected.

**Comment by jonnor** [comment]
Not fixed, just wanted to reference the issue in the commit.

**Comment by bergie** [comment]
Likely related to noflo/noflo#221

**Comment by jonnor** [comment]
Existing solution is OK
