### ISSUE TITLE
IPFS cache/CDN

### ISSUE THREAD

**Issue by bergie** [imgflo/imgflo-server#62]
Currently ImgFlo Server provides a caching interface with Amazon S3. It would be good to explore integration with [IPFS](https://ipfs.io/) as well.

**Comment by bergie** [comment]
One problem is that using IPFS as the cache instead of S3 means we don't know the image's final URL (IPFS hash) before it has been processes, since IPFS URLs are content-addressable.

Two options for working around this:

* Stable address for "job results" via IPNS
* A "in-flight" address that does a permanent redirect to final one once job has completed

**Comment by jonnor** [comment]
Out of scope
